### ISSUE TITLE
Is it possible to create a dashboard from manifest file?

### ISSUE THREAD

**Issue by Nexucis** [perses/perses#2108] opened 2024-07-04 08:32 UTC
Thank you for your answer!

I'll use this as a chance to ask a question which I have been stuck on for the past week. 

I'm trying to implement a Perses dashboard on my react app, which displays TimeCharts from a Prometheus datasource. The thing is, I must implement it in a way that I can provide the dashboard configuration in a manifest file (YAML, JSON). Is creating dashboards in other application from manifest files something that can be done at this stage of development and if so, could you please direct me to the documentation for that or write it here?

_Originally posted by @rasmusvan in https://github.com/perses/website/issues/29#issuecomment-2207099130_

**Comment by Nexucis** [comment] 2024-07-04 08:38
@rasmusvan are you trying to embed the package @perses-dev/dashboard in a react application ?

If so, then if you want to provide the dashboard configuration in a manifest file, you will need to have a backend that will provide this document to the UI.

In case you are using the Perses application (like with the docker image `persesdev/perses`), then you can use the provisioning system that will do exactly what you want. Aka providing a dashboard from a manifest file: https://perses.dev/docs/perses/v0.46.0/user-guides/provisioning.md/

**Comment by rasmusvan** [comment] 2024-07-09 08:45
@Nexucis Yes, I am trying to embed a @perses-dev/dashboards dashboard into my react application using a backend to provide the YAML manifest files to the UI. I am familiar with using percli for providing the files to a specified URL (I have done it locally as well as with demo.perses.dev), but it is the frontend part code, that I am stuck with. How would the link be made between the specific dashboard element and the YAML file I wish to provide to it? 
What would the general component structure have to look like to make this work? It would be nice to have an example for this use case similar to the one provided here for a singular chart (without manifest file support in this case) https://perses.dev/docs/perses/v0.43.0/user-guides/embedding-panels.md/

**Comment by celian-garcia** [comment] 2024-07-13 06:38
Hello, what you are trying to do is not the way we thought of embedded use case. 

Usually, embedded use case is to build panels/dashboard in UI that does not use perses as a backend. Or at least this was my understanding. That's why you don't have an example of your use case.

It doesn't mean that it's not possible though but don't provide yet an easy way. Waiting for it, I can already give you some advices. You will probably have to import more packages than the embedded panel example and reuse dashboard client https://github.com/perses/perses/blob/a017e5c48b8f4987f9a3a372d40be58a1f17911f/ui/app/src/model/dashboard-client.ts#L184 and dashboard component https://github.com/perses/perses/blob/a017e5c48b8f4987f9a3a372d40be58a1f17911f/ui/dashboards/src/components/Dashboard/Dashboard.tsx#L35

That would be good if you provide a minimal reproduction repository to show us where you are and that we can run/explore to help you more precisely.

**Comment by rasmusvan** [comment] 2024-07-15 14:31
Thank you for your answer!

Regarding the reproduction repository, I would appreciate it if you could use the example from “Embedding panels” as a basis (https://perses.dev/docs/perses/v0.43.0/user-guides/embedding-panels.md/).

It is not essential for me to use the Perses backend for providing the manifest files, as retrieving them from the project folder is also a valid option. The key requirement is the ability to switch dashboard manifest files to display different dashboards (meaning you can configure them to contain different panels as well as data from different queries).

**Comment by celian-garcia** [comment] 2024-07-16 06:46
Hello @rasmusvan. Well I'm sorry if it was not clear but I'm asking YOU to provide a repo. So we can guide you from this base.
Did you try already something with the components I mentioned?

**Comment by rasmusvan** [comment] 2024-07-16 11:20
@celian-garcia, thank you for your patience. I’m currently an intern, so I’m still learning.

Here is the minimal version of my progress on implementing dashboards from manifest files. At the moment, it encounters a “PluginRegistryContext not found” error.

https://github.com/rasmusvan/perses-embedded-dashboard-mrr

**Comment by rasmusvan** [comment] 2024-07-17 12:30
I have updated the repo as I got further along. Now the problem is that when I move my cursor on the panel sometimes I get "Cannot read properties of null (reading 'offsetWidth')" error.  Also as of now I cannot find a way to turn the Panel Group name white (like I did for the charts in ChartProvider

**Comment by rasmusvan** [comment] 2024-07-19 08:16
I've been struggling for two days to get the complex example of the datasource manifest to work according to the documentation provided [here](https://perses.dev/docs/perses/v0.46.0/plugin/prometheus.md/). I keep encountering errors such as "Unexpected end of JSON input" or "Unexpected token '<', "<!DOCTYPE "... is not valid JSON" when trying to use a proxy datasource.

I've added the complex datasource manifest, that I was experimenting with, to the reproduction repository: [rasmusvan/perses-embedded-dashboard-mrr](https://github.com/rasmusvan/perses-embedded-dashboard-mrr).

**Comment by celian-garcia** [comment] 2024-07-20 05:13
Hello @rasmusvan I see that you made a good progress on your own! I believe you're not very far. The key with the datasource of kind proxy is that it will use the buildProxyUrl method of the datasource API to know on which path send the different queries. This is useful if you don't want direct urls.

So in this case you need to implement this method to return like /prometheus and configure your web server to redirect this /prometheus to the right URL

**Comment by celian-garcia** [comment] 2024-07-20 05:16
The thing is with all that, you derived from your original objective it seems. You wanted to use the perses backend as Api for datasources/dashboards files and here you are mocking them with the fakeDashboard and fakeDatasource

**Comment by rasmusvan** [comment] 2024-07-20 05:43
Thank you for your input regarding the proxy, I’ll explore the solution in the coming days. Do you have any fix for the Toggle View Mode button (which is used to make a panel bigger) only being clickable once?

**Comment by celian-garcia** [comment] 2024-07-20 06:31
No, for this I'm afraid this is a side effect of what I said in the beginning. Embed a panel is well maintained but not necessarily embed a dashboard. I believe we should discuss internally also on the level of support we want for your use case. If embed a complete dashboard is a use case that we officially support this should be documented for next mates and the full screen mode issue that you have is a bug. You repo would help a lot also for us to build minimal example.

**Comment by rasmusvan** [comment] 2024-07-22 12:43
Thanks to your input, I managed to get data from the proxy datasource working, but I’ve encountered another bug: the pod I’m displaying data for appears to have no name. In my local Perses instance, the name is shown correctly, but when I copy the configuration to my code, the name appears as “{}” when I hover over the graph, even though the data displayed is the same. I have modified the minimal reproduction repository to display this problem.

This issue, like the bug with “Toggle View Mode,” occurs in my code but not in demo.perses.dev, when creating dashboards through the UI or applying them with percli. As I understand it, both my code and the demo website convert dashboard manifests to graphs. Are there any obvious differences between my code and the website source code that could explain this discrepancy?

Lastly, you are more than welcome to use my repo to build the minimal example for dashboard embedding.

**Comment by rasmusvan** [comment] 2024-07-23 09:34
I got the error with pod names not displaying fixed by manually adding `seriesNameFormat: `${podName}`` after all the queries

**Comment by rasmusvan** [comment] 2024-07-24 07:29
I have some additional questions:

1. Is it possible to display both percentages and absolute values (such as bytes or cores) simultaneously, with percentages on the left y-axis and absolute values on the right y-axis?
2. Is there a way to only show the line of the graph, without a panel title and without any data on the x-axis (I understand that the y-axis information can easily be hidden through the manifest file)?

I’ve attached example images for both scenarios.
<img width="1124" alt="image" src="https://github.com/user-attachments/assets/0aae66fe-a949-40c2-85b0-23075bc7bb82">
<img width="354" alt="image" src="https://github.com/user-attachments/assets/ceeecf0e-42aa-48d0-ad79-5c4c9a80eefa">

**Comment by celian-garcia** [comment] 2024-07-25 15:30
Hello @rasmusvan regarding the level of support on embedded dashboard first. 
I discussed with the team and we agree on the fact that in the future it should be a proposed and maintained feature. For example with a proper documentation and good answers to different issues of people.

But for now I'm afraid that it's not at a good level of industrialization. All answers we can give you from now can only be everytime: try and if you think there is a bug (for example the fullscreen mode) file a dedicated issue in the repo with reproduction example and some screens / gif / videos. 


Now regarding your last questions 
- Is it possible to display both percentages and absolute values (such as bytes or cores) simultaneously, with percentages on the left y-axis and absolute values on the right y-axis?
  It's not possible. Feel free to open a dedicated feature request.
- Is there a way to only show the line of the graph, without a panel title and without any data on the x-axis (I understand that the y-axis information can easily be hidden through the manifest file)?
  Not from the dashboard component. Only the panel component have a hide header attribute. 
  
I will close this issue as it starts to be a mess. ^^'

**Closed** 2024-07-25 15:30 UTC
